import argparse

ap = argparse.ArgumentParser()
ap.add_argument("-dni", "--dni", required=True, default='11111111', help="Random DNI: Default value :11111111")
args = vars(ap.parse_args())
num=int(args["dni"])
print("....................................................")
print("....................................................")
resto = num % 23
if(resto == 0): print("Tu DNI es "+str(num)+"-T")
elif(resto==1): print("Tu DNI es "+str(num)+"-R")
elif(resto==2): print("Tu DNI es "+str(num)+"-W")
elif(resto==3): print("Tu DNI es "+str(num)+"-A")
elif(resto==4): print("Tu DNI es "+str(num)+"-G")
elif(resto==5): print("Tu DNI es "+str(num)+"-M")
elif(resto==6): print("Tu DNI es "+str(num)+"-Y")
elif(resto==7): print("Tu DNI es "+str(num)+"-F")
elif(resto==8): print("Tu DNI es "+str(num)+"-P")
elif(resto==9): print("Tu DNI es "+str(num)+"-D")
elif(resto==10): print("Tu DNI es "+str(num)+"-X")
elif(resto==11): print("Tu DNI es "+str(num)+"-B")
elif(resto==12): print("Tu DNI es "+str(num)+"-N")
elif(resto==13): print("Tu DNI es "+str(num)+"-J")
elif(resto==14): print("Tu DNI es "+str(num)+"-Z")
elif(resto==15): print("Tu DNI es "+str(num)+"-S")
elif(resto==16): print("Tu DNI es "+str(num)+"-Q")
elif(resto==17): print("Tu DNI es "+str(num)+"-V")
elif(resto==18): print("Tu DNI es "+str(num)+"-H")
elif(resto==19): print("Tu DNI es "+str(num)+"-L")
elif(resto==20): print("Tu DNI es "+str(num)+"-C")
elif(resto==21): print("Tu DNI es "+str(num)+"-K")
elif(resto==22): print("Tu DNI es "+str(num)+"-E")
else:
    print("Igual no es valido...")
 
print("....................................................")
print("....................................................")
